/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class helloWindow */

#ifndef _Included_helloWindow
#define _Included_helloWindow
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     helloWindow
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_helloWindow_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     helloWindow
 * Method:    hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_helloWindow_hello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
