/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_digimead_HelloWorldJNIwithRegisterNatives */

#ifndef _Included_org_digimead_HelloWorldJNIwithRegisterNatives
#define _Included_org_digimead_HelloWorldJNIwithRegisterNatives
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
