/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jni_java_printN */

#ifndef _Included_org_jni_java_printN
#define _Included_org_jni_java_printN
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jni_java_printN
 * Method:    print20
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jni_java_printN_print20
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
