/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jniLearning_factorial_Factorial */

#ifndef _Included_org_jniLearning_factorial_Factorial
#define _Included_org_jniLearning_factorial_Factorial
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jniLearning_factorial_Factorial
 * Method:    run
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_jniLearning_factorial_Factorial_run
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_jniLearning_factorial_Factorial
 * Method:    hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jniLearning_factorial_Factorial_hello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
