/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jniLearning_utils_Fibonacci */

#ifndef _Included_org_jniLearning_utils_Fibonacci
#define _Included_org_jniLearning_utils_Fibonacci
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jniLearning_utils_Fibonacci
 * Method:    compute
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_jniLearning_utils_Fibonacci_compute
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
