/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ie_agisoft_printN */

#ifndef _Included_ie_agisoft_printN
#define _Included_ie_agisoft_printN
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ie_agisoft_printN
 * Method:    printN
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ie_agisoft_printN_printN
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
